Feature/node 24 jatkot (#481)
* DPO-3603 Päivitetään Node versio 22 -> 24
- "@digitraffic/common": "2026.1.23-1",
- some biome fixes
- fix cloudfront build
- Lambda bunde dependency and size test to esbuild
- refactor some projects
- Update dep tester
- Fixes to node 24 etc.
- Update common

* fix winter-navigation tests

Co-authored-by: Ilari Junnonen <ilari.junnonen@solita.fi>

diff --git a/lib/digitraffic-common/lefthook.yml b/lib/digitraffic-common/lefthook.yml
--- a/lib/digitraffic-common/lefthook.yml
+++ b/lib/digitraffic-common/lefthook.yml
@@ -1,4 +1,3 @@
-# EXAMPLE USAGE:
 #
 #   Refer for explanation to following link:
 #   https://lefthook.dev/configuration/
@@ -9,8 +8,9 @@ pre-commit:
     01-sort-package-json:
       #glob: "*.{ts,yml,yaml,md,json,html}"
       run: |
+        set -e  # stop on error except where explicitly allowed
         # Reorder package.json
-        pnpm run sort:package-json
+        pnpm run format:package-json
         # Re-add package.json if it was modified
         git add package.json || true
     02-biomejs-check:
@@ -18,6 +18,6 @@ pre-commit:
       run: |
         # Run Biome on staged files, auto-fixing issues
         # pnpm format:fix-staged || true; # Errors are ignored to allow commit to proceed even if Biome finds issues
-        pnpm format:fix-staged; # Dont allow errors to be ignored, commit should fail if Biome finds issues
+        pnpm run format:fix-staged; # Dont allow errors to be ignored, commit should fail if Biome finds issues
         # Re-add any files that Biome fixed. Sometimes deleted files cause git add to fail, so we ignore errors.
         git add $(git diff --name-only --cached) || true
