DPO-3436 Korvataan ESLint BiomeJS:llä (#456)
* DPO-3436 Korvataan ESLint BiomeJS:llä
* DPO-3497 Korjataan digitraffic-common lefthook subtree projekteissa

diff --git a/lib/digitraffic-common/lefthook.yml b/lib/digitraffic-common/lefthook.yml
--- a/lib/digitraffic-common/lefthook.yml
+++ b/lib/digitraffic-common/lefthook.yml
@@ -6,8 +6,18 @@
 pre-commit:
   parallel: false
   commands:
-    deno-fmt:
+    01-sort-package-json:
       #glob: "*.{ts,yml,yaml,md,json,html}"
-      run: | # Runs even when deno fmt fails with: No target files found.
-        pnpm deno fmt {staged_files} || true;
-        git add {staged_files} || true;
+      run: |
+        # Reorder package.json
+        pnpm run sort:package-json
+        # Re-add package.json if it was modified
+        git add package.json || true
+    02-biomejs-check:
+      #glob: "*.{ts,yml,yaml,md,json,html}"
+      run: |
+        # Run Biome on staged files, auto-fixing issues
+        # pnpm format:fix-staged || true; # Errors are ignored to allow commit to proceed even if Biome finds issues
+        pnpm format:fix-staged; # Dont allow errors to be ignored, commit should fail if Biome finds issues
+        # Re-add any files that Biome fixed. Sometimes deleted files cause git add to fail, so we ignore errors.
+        git add $(git diff --name-only --cached) || true
