DPO-3017 Deno fmt formatterin käyttöönotto prettierin tilalle

diff --git a/common/git-hooks/pre-commit b/common/git-hooks/pre-commit
--- a/common/git-hooks/pre-commit
+++ b/common/git-hooks/pre-commit
@@ -3,10 +3,22 @@
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
 
-# Invoke the "rush prettier" custom command to reformat files whenever they
-# are committed. The command is defined in common/config/rush/command-line.json
-# and uses the "rush-prettier" autoinstaller.
-node common/scripts/install-run-rush.js prettier || exit $?
+# run formatting to all files and add reformatted files to staging to be committed
+if ! command -v deno 2>&1 >/dev/null
+then
+    echo "deno command could not be found. Install e.g. brew install deno."
+    exit 1
+fi
+
+FILES=$(deno fmt 2>&1)
+if [ -n "$FILES" ]; then
+  CHANGES=$(echo $FILES | tail -n 1)
+  echo $CHANGES
+  echo "Adding (git add) formatted files"
+  echo "$FILES" | sed '$d'
+  echo "$FILES" | sed '$d' | xargs -I "{}" git add "{}"
+  echo "Done"
+fi
 
 # Check package dependencies
 node common/scripts/install-run-rush.js repo:check-dependencies || exit $?
