DPO-3653 check if configs are found

diff --git a/.github/workflows/install.yml b/.github/workflows/install.yml
--- a/.github/workflows/install.yml
+++ b/.github/workflows/install.yml
@@ -80,13 +80,20 @@ jobs:
             cat digitraffic-ci/aws/cdk/install-config.json >> $GITHUB_OUTPUT
             echo "EOF" >> $GITHUB_OUTPUT
 
-      - name: Set environment variables
+      - name: Set environment variables for ${{ github.event.inputs.application }}
         id: environment
+        env:
+          INSTALL_CONFIG: ${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application] }}
+          DOMAIN: ${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application].domain }}
+          STACK: ${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application].stack }}
+          DIRECTORY: ${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application].directory }}
         run: |
-            export INSTALL_CONFIG=${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application] }}
-            export DOMAIN=${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application].domain }}
-            export STACK=${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application].stack }}
-            export DIRECTORY=${{ fromJson(steps.install-config.outputs.config).projects[github.event.inputs.application].directory }}            
+            if [ "$INSTALL_CONFIG" == "" ]; then
+              echo "Error: Application ${{ github.event.inputs.application }} not found in install config!"
+              echo "Error: Application ${{ github.event.inputs.application }} not found in install config!" >> $GITHUB_STEP_SUMMARY
+
+              exit 1
+            fi;
 
             # by default, directory is same as domain
             if [ "$DIRECTORY" == "" ]; then
@@ -107,6 +114,13 @@ jobs:
       - name: Read SBOM config
         id: sbom-config
         run: |
+            if [ ! -f "digitraffic-ci/aws/sbom/${{ steps.environment.outputs.domain }}.json" ]; then
+              echo "Error: SBOM config for domain ${{ steps.environment.outputs.domain }} not found!"
+              echo "Error: SBOM config for domain ${{ steps.environment.outputs.domain }} not found!" >> $GITHUB_STEP_SUMMARY
+
+              exit 1
+            fi;
+
             echo "config<<EOF" >> $GITHUB_OUTPUT
             cat digitraffic-ci/aws/sbom/${{ steps.environment.outputs.domain }}.json >> $GITHUB_OUTPUT
             echo "EOF" >> $GITHUB_OUTPUT
